title : API Evangelist

safe: true
lsi: false
pygments: true

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

pagination: 10
paginate_path: "blog/page:num"

production_url : http://design.apievangelist.com

BASE_PATH : http://design.apievangelist.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
