title:        API Evangelist
description:  A network of research sites dedicated to the technology, business, and politics of APIs.
url:          http://apievangelist.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 25
paginate_path: "/blog/page:num"

production_url : http://apievangelist.com

BASE_PATH : http://apievangelist.com

categories_path : /categories.html
tags_path : /tags.html

image : http://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png
imagesecure : https://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png
